import "./globals.css";

import localFont from "next/font/local";
import { DM_Sans } from "next/font/google";

export const shoble = localFont({
  src: [
    {
      path: "fonts/shoble/Shnobel-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/shoble/Shnobel-Oblique.woff",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-shoble",
});

export const dmSans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${dmSans.className} ${shoble.variable}`}>
      <body className="bg-amber-50 text-slate-900">{children}</body>
    </html>
  );
}
