import "./globals.css";

import localFont from "next/font/local";

export const shoble = localFont({
  src: [
    {
      path: "fonts/shoble/Shnobel-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "fonts/shoble/Shnobel-Oblique.woff",
      weight: "400",
      style: "italic",
    },
  ],
  variable: "--font-shoble",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={shoble.variable}>
      <body className="bg-amber-50">{children}</body>
    </html>
  );
}
